### ISSUE TITLE
Makefile lint command

### ISSUE THREAD

**Issue by obalunenko** [IvanTerekh/go-skeleton#7]
Suggest to add more linters here

 at least:

- go vet (https://golang.org/cmd/vet/)
- golint (golang.org/x/lint/golint)
- errcheck (https://github.com/kisielk/errcheck)

in advance:
- golangci-lint (https://github.com/golangci/golangci-lint - the best one, cause it aggregates a lot of linters and run them really fast)

**Comment by obalunenko** [comment]
for imports suggest to use this one:
https://github.com/Bubblyworld/gogroup

**Comment by ivanterekh** [comment]
> for imports suggest to use this one:
> https://github.com/Bubblyworld/gogroup

Does not seem to be better than [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports) which is already used.

**Comment by obalunenko** [comment]
it works faster than goimports
```
core on  obalunenko-T20896-multiple-statements [⇡!] on 🐳 v18.09.2 took 12s
➜ goimports -w  --local bitx/ src/bitx/banking/banks/bni/exporter_test.go

core on  obalunenko-T20896-multiple-statements [⇡!] on 🐳 v18.09.2 took 2s
➜ gogroup -order std,other,prefix=bitx/ --rewrite src/bitx/banking/banks/bni/exporter_test.go
Fixed src/bitx/banking/banks/bni/exporter_test.go
```

For the same file:
- goimports -12s
- gogroups - 2s
